  name: Java CI with PostgreSQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Run database migrations
      run: |
        psql -h localhost -U postgres -d postgres -c 'CREATE DATABASE meu_banco_de_dados;'
        psql -h localhost -U postgres -d meu_banco_de_dados -f src/main/resources/db/migration/schema.sql

    - name: Deploy
      run: echo "Deploying your application..."
